# REC控制器配置
rec_controller:
  # 通信方式: 'serial' 或 'ethernet_ip'
  comm_type: 'serial'
  
  # IP地址配置（用于网络连接）
  ip_address: "192.168.0.1"
  subnet_mask: "255.255.255.0"
  gateway: "0.0.0.0"

  # 串口配置
  serial:
    port: 'COM6'
    baudrate: 115200

  # 网络配置
  ethernet_ip:
    ip_address: "192.168.0.1"
    subnet_mask: "255.255.255.0"
    gateway: "0.0.0.0"

# EC单元配置
ec_units:
  count: 2  # EC接续单元数量

# 通信配置
communication:
  timeout: 3.0
  retry_count: 3

# 日志配置
logging:
  level: 'INFO'
  file: 'rec_controller.log'